defaults:
  - base_config
  - override hydra/job_logging: custom-simplest
  - _self_

hydra:
  run:
    dir: ./output/${exp_id}
  output_subdir: eval-${now:%Y-%m-%d_%H-%M-%S}-hydra

avs_train: true
model: small_44k_avs

exp_id: ${model}
dataset: audiocaps
duration_s: 8.0

# for inference, this is the per-GPU batch size
batch_size: 4
output_name: null
